### PR TITLE
fix cloning instructions

### PR DESCRIPTION
**Pull request by stas00**
This PR adds a missing `cd arctic_shift` and provides an alternative clone oneliner.

### CODE REVIEW

**Comment by ArthurHeitmann** [comment]
Good idea. Whilst you are at it, you can drop the first clone command and only keep the --recursive one.

**Comment by stas00** [comment]
done.

**Comment by ArthurHeitmann** [comment]
Now you also removed the `cd ` 😄. Up to you if you want to add it again or keep it as is

**Comment by stas00** [comment]
re-added

**Comment by ArthurHeitmann** [comment]
Alright, looks good

**Pull request merged**
